### ISSUE TITLE
Renaming Branches for consistency in course

### ISSUE THREAD

**Issue by dtauer** [stevekinney/supertasker#2]
To stay consistent with the other repos, can you rename the following branches:

- [x] Rename `tasks-slice-and-hooks` to `user-slice-exercise`
- [x] Rename `user-slice-exercise-solutionj` -> `user-slice-solution`

Thanks!

**Comment by stevekinney** [comment]
Done!

**Comment by dtauer** [comment]
Woo hoo! Thanks! Looking forward to seeing you next week!
